apiVersion: v1
kind: Service
metadata:
  namespace: data
  labels:
    app: simple-shop
    component: document
    team: platform
  name: document
spec:
  ports:
  - port: 5432
  selector:
    app: simple-shop
    component: document
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: document
spec:
  template:
    metadata:
      namespace: data
      labels:
        app: simple-shop
        component: document
        team: platform
    spec:
      containers:
      - name: document
        image: postgres:alpine
        env:
        - name: POSTGRES_DB
          value: TestDb
        - name: POSTGRES_PASSWORD
          value: ABC123!!
        - name: POSTGRES_USER
          value: application